### ISSUE TITLE
Multiple Paths Not Working with wild cards

### ISSUE THREAD

**Issue by sarathkcm** [ItsLofus/webpack-raw-bundler#1]
Hello. 

Thank you for the awesome package.!!  👍 

Came across an issue though:

```Json
            bundles: [
                "AngularJS.js",
            ],
            "AngularJS.js": [
                {
                    path: path.resolve(__dirname, "Angular/AngularJS/module.js")
                },
                {
                    path: path.resolve(__dirname, "Angular/AngularJS/Wrappers/wrapper.js")
                }]
```
The above configuration works...!

```Json
            bundles: [
                "AngularJS.js",
            ],
            "AngularJS.js": [
                {
                    path: path.resolve(__dirname, "Angular/AngularJS/module.js")
                },
                {
                    path: path.resolve(__dirname, "Angular/AngularJS/Wrappers/") + "/*.js",
                }]
```
The above one doesn't. It will bundle only the module.js file

```Json

            bundles: [
                "AngularJS.js",
            ],
            "AngularJS.js": [
                {
                    path: path.resolve(__dirname, "Angular/AngularJS/Wrappers/") + "/*.js",
                },
                {
                    path: path.resolve(__dirname, "Angular/AngularJS/module.js")
                }]
```

It is not a problem with how I defined the path.resolve + wildcard string, because the above configuration bundles wrapper.js. However, module.js is not bundled.

I hope you will check this issue. I am planning to use this plugin in a project I am starting next week.

Regards,
Sarath

**Comment by ItsLofus** [comment]
baaah I totally know what's going on here it's my fault.

This will be resolved, in the worst case, on monday, sorry about the inconvenience.

**Comment by sarathkcm** [comment]
Thank you... :) 👍

**Comment by ItsLofus** [comment]
@sarathkcm Everything should be resolved now 👍 
Let me know if anything else comes up.

**Comment by sarathkcm** [comment]
Verified working. thank you for promptly fixing it.

**Comment by sarathkcm** [comment]
@ItsLofus Is there a way to enable watch for file changes? 'webpack --watch' does not watch for files loaded using webpack-raw-bundler.

**Comment by ItsLofus** [comment]
not as of now, it's a feature im looking into
