### ISSUE TITLE
Raw bundler not bundling any js.

### ISSUE THREAD

**Issue by Quadriphobs1** [ItsLofus/webpack-raw-bundler#2]
I some series of JQuery Plugins and i use the webpack-raw-bundler but in the inpect i didn't see any trace of the the script tag nor see imported files working

**Comment by ItsLofus** [comment]
This is very vague, I think you're confused on what this plugin does. Please check the usage example. 

If you need more debugging assistance you can post what you have tried. However, it seems you may be forgetting to include your exported bundle, or are using it in some other invalid way.
